-- File auto generated by purescript-bridge! --
module TestData where

import Prelude

import ConstrIndices (class HasConstrIndices, fromConstr2Index)
import Data.Generic.Rep (class Generic)
import Data.Maybe (Maybe(Nothing, Just))
import Data.Tuple (Tuple(Tuple))
import FromData (class FromData, genericFromData)
import ToData (class ToData, genericToData)

data TwoRecords
  = FirstRecord
    { _fra :: String
    , _frb :: Int
    }
  | SecondRecord
    { _src :: Int
    , _srd :: Array Int
    }

derive instance Generic TwoRecords _

instance HasConstrIndices TwoRecords where
  constrIndices _ = fromConstr2Index [Tuple "FirstRecord" 0,Tuple "SecondRecord" 1]

instance ToData TwoRecords where
  toData x = genericToData x

instance FromData TwoRecords where
  fromData pd = genericFromData pd
