# This file has been generated by node2nix 1.9.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@ngua/cardano-serialization-lib-browser-9.1.2" = {
      name = "_at_ngua_slash_cardano-serialization-lib-browser";
      packageName = "@ngua/cardano-serialization-lib-browser";
      version = "9.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ngua/cardano-serialization-lib-browser/-/cardano-serialization-lib-browser-9.1.2.tgz";
        sha512 = "0KkS3vCwrK8Yxs+yuoFJ05Ou5r0AZJNTWks9otP5h9ODsTUpkgJDb3lVmflJmSB0KnA9JvF3AmcN/swXj/yw+A==";
      };
    };
    "@ngua/cardano-serialization-lib-nodejs-9.1.2" = {
      name = "_at_ngua_slash_cardano-serialization-lib-nodejs";
      packageName = "@ngua/cardano-serialization-lib-nodejs";
      version = "9.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ngua/cardano-serialization-lib-nodejs/-/cardano-serialization-lib-nodejs-9.1.2.tgz";
        sha512 = "6xpp5Xjcqm9eHIrKBUmmIeZV6n0OeK6t8vCyQzF8KcHEQiknAcIcoIq/wf7sEcLV3ohwn945QCKkM3rKsKF5FA==";
      };
    };
    "big-integer-1.6.51" = {
      name = "big-integer";
      packageName = "big-integer";
      version = "1.6.51";
      src = fetchurl {
        url = "https://registry.npmjs.org/big-integer/-/big-integer-1.6.51.tgz";
        sha512 = "GPEid2Y9QU1Exl1rpO9B2IPJGHPSupF5GnVIP0blYvNOMer2bTvSWs1jGOUg04hTmu67nmLsQ9TBo1puaotBHg==";
      };
    };
    "bufferutil-4.0.5" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.5.tgz";
        sha512 = "HTm14iMQKK2FjFLRTM5lAVcyaUzOnqbPtesFIvREgXpJHdQm8bWS+GkQgIkfaBYRHuCnea7w8UVNfwiAQhlr9A==";
      };
    };
    "node-gyp-build-4.4.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.4.0.tgz";
        sha512 = "amJnQCcgtRVw9SvoebO3BKGESClrfXGCUTX9hSn1OuGQTQBOZmVd0Z0OlecpuRksKvbsUqALE8jls/ErClAPuQ==";
      };
    };
  };
  args = {
    name = "purescript-bridge-rountrip-test";
    packageName = "purescript-bridge-rountrip-test";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@ngua/cardano-serialization-lib-browser-9.1.2"
      sources."@ngua/cardano-serialization-lib-nodejs-9.1.2"
      sources."big-integer-1.6.51"
      sources."bufferutil-4.0.5"
      sources."node-gyp-build-4.4.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
